### ISSUE TITLE
Layout kích hoạt thành viên bị rớt 

### ISSUE THREAD

**Issue by nmquyet** [thuatnha/VipLink#2]
Trang kich_hoat_thanh_vien.html, phần banner bị rớt xuống dưới trên màn hình to 
![screen shot 2016-04-27 at 4 10 28 pm](https://cloud.githubusercontent.com/assets/690483/14847413/b38dd88c-0c92-11e6-86ba-37f2ea19a7fd.png)

**Comment by thuatnha** [comment]
Đã chỉnh lại grid page.
